apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
  namespace: tidb-cluster
spec:
  clusters:
  - name: basic
  prometheus:
    baseImage: registry.cn-beijing.aliyuncs.com/prom/prometheus
    version: v2.18.1
  grafana:
    baseImage: registry.cn-beijing.aliyuncs.com/grafana/grafana
    version: 6.1.6
  initializer:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tidb-monitor-initializer
    version: v4.0.8
  reloader:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
