apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
  namespace: tidb-cluster
spec:
  version: v4.0.8
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  pd:
    enableDashboardInternalProxy: true
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/pd
    replicas: 1
    requests:
      storage: "1Gi"
    config:
      replication:
        max-replicas: 1
        enable-placement-rules: true
  tikv:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tikv
    replicas: 1
    requests:
      storage: "1Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tidb
    replicas: 1
    service:
      type: NodePort
      nodePort: 30002
    config: {}
  tiflash:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tiflash
    maxFailoverCount: 3
    replicas: 1
    storageClaims:
    - resources:
        requests:
          storage: 1Gi